# Generated by Django 5.1 on 2024-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Пароль")),
            ],
            options={
                "verbose_name": "Учетная_запись_электронной_почты",
                "verbose_name_plural": "Учетные_записи_электронных_почт",
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_id",
                    models.IntegerField(default=True, verbose_name="Идентификатор"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Тема")),
                (
                    "date_email",
                    models.CharField(
                        blank=True, default=None, max_length=200, verbose_name="Дата"
                    ),
                ),
                (
                    "from_email",
                    models.CharField(blank=True, default=None, max_length=200),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Тип",
                    ),
                ),
                ("body", models.TextField(blank=True, default=None, null=True)),
                (
                    "attachments",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Вложения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение_электронной_почты",
                "verbose_name_plural": "Сообщении_электронных_почт",
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
            options={
                "verbose_name": "Заголовок",
                "verbose_name_plural": "Заголовки",
            },
        ),
    ]
